steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/summit-enterprise-workshop/router-v2_4_0',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/summit-enterprise-workshop/router-v2_4_0']
  # Deploy container image to Cloud Run
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args:
  #     [
  #       'run',
  #       'deploy',
  #       'router-v2_0-preview',
  #       '--image',
  #       'gcr.io/summit-enterprise-workshop/router-v2_0-preview',
  #       '--allow-unauthenticated',
  #       '--region',
  #       'europe-north1',
  #       # '--update-env-vars',
  #       # 'APOLLO_KEY=${_APOLLO_KEY},APOLLO_GRAPH_REF=${_APOLLO_GRAPH_REF}',
  #     ]
images:
  - gcr.io/summit-enterprise-workshop/router-v2_4_0
